// Generated by Haxe 4.3.6

#pragma warning disable 109, 114, 219, 429, 168, 162
public class QuickSort : global::haxe.lang.HxObject {
	
	public QuickSort(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public QuickSort() {
		global::QuickSort.__hx_ctor__QuickSort(this);
	}
	
	
	protected static void __hx_ctor__QuickSort(global::QuickSort __hx_this) {
	}
	
	
	public static global::Array<int> quickSort(global::Array<int> arr) {
		unchecked {
			global::QuickSort.quickSortHelper(arr, 0, ( arr.length - 1 ));
			return arr;
		}
	}
	
	
	public static void quickSortHelper(global::Array<int> arr, int low, int high) {
		unchecked {
			if (( low < high )) {
				int pi = global::QuickSort.partition(arr, low, high);
				global::QuickSort.quickSortHelper(arr, low, ( pi - 1 ));
				global::QuickSort.quickSortHelper(arr, ( pi + 1 ), high);
			}
			
		}
	}
	
	
	public static int partition(global::Array<int> arr, int low, int high) {
		unchecked {
			int pivot = arr[high];
			int i = ( low - 1 );
			{
				int _g = low;
				int _g1 = high;
				while (( _g < _g1 )) {
					int j = _g++;
					if (( arr[j] < pivot )) {
						 ++ i;
						global::QuickSort.swap(arr, i, j);
					}
					
				}
				
			}
			
			global::QuickSort.swap(arr, ( i + 1 ), high);
			return ( i + 1 );
		}
	}
	
	
	public static void swap(global::Array<int> arr, int i, int j) {
		int temp = arr[i];
		arr[i] = arr[j];
		arr[j] = temp;
	}
	
	
}


